name: 'Bikeclub Dev'
description: 'Provides development tools. DO NOT install in production environment.'
type: 'Administration'
install:
  # Contrib.
  - devel
  - devel_kint_extras
  - config_delete
  - config_ignore  
  - config_single_export
  - kint
  - masquerade
config:
  strict: false
  import:
    devel: '*'
    config_ignore: '*'
